# Generated by Django 5.0 on 2024-01-09 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttable',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
