# Generated by Django 5.0 on 2024-01-16 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0002_paymenttable_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='pincode',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='paymenttable',
            name='itemId',
            field=models.CharField(default='', max_length=10),
        ),
    ]
