# Generated by Django 5.0 on 2024-01-16 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0003_alter_address_pincode_alter_paymenttable_itemid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='id',
        ),
        migrations.RemoveField(
            model_name='paymenttable',
            name='id',
        ),
        migrations.AlterField(
            model_name='address',
            name='userId',
            field=models.EmailField(max_length=254, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='paymenttable',
            name='transactionId',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
