# Generated by Django 4.2.3 on 2023-10-26 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventId', models.CharField(default='', max_length=10)),
                ('name', models.CharField(default='', max_length=20)),
                ('about', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='EventTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventId', models.CharField(max_length=10, null=True)),
                ('user_id', models.IntegerField()),
                ('ca_code', models.CharField(max_length=10)),
                ('transactionId', models.CharField(max_length=25)),
                ('verified', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField()),
                ('username', models.CharField(max_length=13)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=13)),
                ('college', models.CharField(max_length=100, null=True)),
                ('year', models.CharField(max_length=5, null=True)),
                ('CA', models.TextField(null=True)),
            ],
        ),
    ]
