# Generated by Django 3.1.6 on 2023-07-29 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='CA',
            field=models.TextField(default='r4h4xx'),
        ),
    ]
