# Generated by Django 3.1.6 on 2023-07-29 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20230729_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='CA',
            field=models.TextField(default='nlnzea'),
        ),
    ]
