# Generated by Django 3.1.6 on 2023-07-29 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20230729_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='CA',
            field=models.TextField(default='oabh1v'),
        ),
    ]
