# Generated by Django 3.1.6 on 2023-07-29 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20230729_1659'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='name',
            new_name='username',
        ),
        migrations.AlterField(
            model_name='profile',
            name='CA',
            field=models.TextField(default='hu4a6p'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(max_length=13),
        ),
    ]
