# Generated by Django 3.1.6 on 2023-07-30 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20230730_0522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='CA',
            field=models.TextField(default='vx2ixj'),
        ),
    ]
