# Generated by Django 4.2.3 on 2023-08-12 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20230730_1027'),
    ]

    operations = [
    ]
