# Generated by Django 4.2.3 on 2023-11-16 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_profile_college_alter_profile_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='college',
            field=models.CharField(max_length=100, null=True),
        )
    ]
