# Generated by Django 5.0 on 2023-12-04 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_profile_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institutionType', models.CharField(max_length=255)),
                ('instiName', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='year',
            new_name='joinYear',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='college',
        ),
        migrations.AddField(
            model_name='profile',
            name='gradYear',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='instituteID',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='stream',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
