# Generated by Django 4.2.3 on 2023-12-18 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_institute_rename_year_profile_joinyear_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='id',
        ),
        migrations.RemoveField(
            model_name='eventtable',
            name='ca_code',
        ),
        migrations.RemoveField(
            model_name='eventtable',
            name='id',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='CA',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='id',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='userId',
        ),
        migrations.AlterField(
            model_name='event',
            name='eventId',
            field=models.CharField(default='', max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='eventtable',
            name='transactionId',
            field=models.CharField(max_length=25, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='institute',
            name='institutionType',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(max_length=254, primary_key=True, serialize=False),
        ),
    ]
