# Generated by Django 4.2.3 on 2023-12-27 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_remove_event_about_remove_eventtable_user_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='maxMember',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='event',
            name='minMember',
            field=models.IntegerField(default=1),
        ),
    ]
