# Generated by Django 4.2.3 on 2024-01-03 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_event_maxmember_event_minmember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
