# Generated by Django 4.2.3 on 2024-01-06 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_eventtable_cacode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventtable',
            name='transactionId',
            field=models.TextField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='profile',
            name='stream',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='username',
            field=models.TextField(),
        ),
    ]
