# Generated by Django 4.2.3 on 2024-01-19 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_alter_eventtable_transactionid_alter_profile_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventtable',
            name='eventId',
            field=models.CharField(db_index=True, max_length=10, null=True),
        ),
    ]
