# Generated by Django 4.2.3 on 2024-01-19 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_alter_eventtable_eventid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='eventId',
            field=models.CharField(db_index=True, default='', max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, primary_key=True, serialize=False),
        ),
    ]
